//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCMSNotifQueue
    {
        public int NotifId { get; set; }
        public string DeviceToken { get; set; }
        public string UniqueId { get; set; }
        public string UpdateKey { get; set; }
        public string NotifDate { get; set; }
    }
}
