//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCMSNotifMaster
    {
        public int NotifId { get; set; }
        public string NotifText { get; set; }
        public string NotifKey { get; set; }
        public Nullable<System.DateTime> NotifDate { get; set; }
        public Nullable<bool> NotifStatus { get; set; }
    }
}
