//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDevice
    {
        public int DeviceID { get; set; }
        public string DeviceToken { get; set; }
        public string ApplicationName { get; set; }
        public string OSVersion { get; set; }
        public Nullable<System.DateTime> RegisterationTime { get; set; }
        public string UniqueID { get; set; }
        public string MachineName { get; set; }
        public string UserAgent { get; set; }
        public string Lang { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> LastLogTime { get; set; }
        public Nullable<int> LogCount { get; set; }
    }
}
