//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Core.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_tr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_tr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Core.Language.Resource_tr-TR", typeof(Resource_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif/Pasif.
        /// </summary>
        public static string ActivePassive {
            get {
                return ResourceManager.GetString("ActivePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ekle.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Girişi.
        /// </summary>
        public static string AdministratorLogin {
            get {
                return ResourceManager.GetString("AdministratorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string BitisTarih {
            get {
                return ResourceManager.GetString("BitisTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Metni.
        /// </summary>
        public static string CampaignBody {
            get {
                return ResourceManager.GetString("CampaignBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya No:.
        /// </summary>
        public static string CampaignNo {
            get {
                return ResourceManager.GetString("CampaignNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalar.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Arkaplan.
        /// </summary>
        public static string CategoryBackground {
            get {
                return ResourceManager.GetString("CategoryBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Görsel.
        /// </summary>
        public static string CategoryImage {
            get {
                return ResourceManager.GetString("CategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Yönetimi.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Kategorisi.
        /// </summary>
        public static string CategoryTag {
            get {
                return ResourceManager.GetString("CategoryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Tipi.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Seçiniz.
        /// </summary>
        public static string Clickheretoupload {
            get {
                return ResourceManager.GetString("Clickheretoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        public static string CopyrightMigrosCMS {
            get {
                return ResourceManager.GetString("CopyrightMigrosCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Simgesi.
        /// </summary>
        public static string DeviceToken {
            get {
                return ResourceManager.GetString("DeviceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Tipi.
        /// </summary>
        public static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterim Sırası.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kataloğu İndir.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstra Veri.
        /// </summary>
        public static string ExtraData {
            get {
                return ResourceManager.GetString("ExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalara Git.
        /// </summary>
        public static string GotoCampaings {
            get {
                return ResourceManager.GetString("GotoCampaings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yolu.
        /// </summary>
        public static string ImageLink {
            get {
                return ResourceManager.GetString("ImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntü Adı.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntü Yolu.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resimler.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yükle.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Oranı.
        /// </summary>
        public static string IndirimOran {
            get {
                return ResourceManager.GetString("IndirimOran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kullanıcı adı veya şifre.
        /// </summary>
        public static string InvalidUserErrorMessage {
            get {
                return ResourceManager.GetString("InvalidUserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Başlığı.
        /// </summary>
        public static string Itembaşlık {
            get {
                return ResourceManager.GetString("Itembaşlık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanç Arka Plan.
        /// </summary>
        public static string KazancBackground {
            get {
                return ResourceManager.GetString("KazancBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanç Tipi.
        /// </summary>
        public static string KazancTipi {
            get {
                return ResourceManager.GetString("KazancTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string KazancTitle {
            get {
                return ResourceManager.GetString("KazancTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine Adı.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migros.
        /// </summary>
        public static string Migros {
            get {
                return ResourceManager.GetString("Migros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori Arkaplan.
        /// </summary>
        public static string NewCategoryBackground {
            get {
                return ResourceManager.GetString("NewCategoryBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori Görsel.
        /// </summary>
        public static string NewCategoryBoardImage {
            get {
                return ResourceManager.GetString("NewCategoryBoardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderim Tarihi.
        /// </summary>
        public static string NotifDate {
            get {
                return ResourceManager.GetString("NotifDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Cihaz.
        /// </summary>
        public static string NotificationDevice {
            get {
                return ResourceManager.GetString("NotificationDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Cihazları.
        /// </summary>
        public static string NotificationDevices {
            get {
                return ResourceManager.GetString("NotificationDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Detayı.
        /// </summary>
        public static string OfferDesc {
            get {
                return ResourceManager.GetString("OfferDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Adı.
        /// </summary>
        public static string OfferName {
            get {
                return ResourceManager.GetString("OfferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif No(OfferNo).
        /// </summary>
        public static string OfferNo {
            get {
                return ResourceManager.GetString("OfferNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Sürümü.
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yolu.
        /// </summary>
        public static string PdfPath {
            get {
                return ResourceManager.GetString("PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Yükle.
        /// </summary>
        public static string PdfUpload {
            get {
                return ResourceManager.GetString("PdfUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya No.
        /// </summary>
        public static string PromoNo {
            get {
                return ResourceManager.GetString("PromoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Gönder.
        /// </summary>
        public static string PushNotification {
            get {
                return ResourceManager.GetString("PushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni hatırla.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Lütfen Doldurunuz.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı gereklidir.
        /// </summary>
        public static string requiredID {
            get {
                return ResourceManager.GetString("requiredID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre gereklidir.
        /// </summary>
        public static string requiredPassword {
            get {
                return ResourceManager.GetString("requiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Seç.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim gönder.
        /// </summary>
        public static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Signmein {
            get {
                return ResourceManager.GetString("Signmein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu Kapat.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin.
        /// </summary>
        public static string TextBody {
            get {
                return ResourceManager.GetString("TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yükleme.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel Yükle.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string UrunAdi {
            get {
                return ResourceManager.GetString("UrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Gör.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfada göster.
        /// </summary>
        public static string VisibleOnMainPage {
            get {
                return ResourceManager.GetString("VisibleOnMainPage", resourceCulture);
            }
        }
    }
}
